# Generated by Django 5.0.2 on 2024-05-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Code')),
                ('item', models.CharField(max_length=128, unique=True, verbose_name='Item')),
                ('description', models.CharField(max_length=512, verbose_name='Description')),
                ('stock', models.SmallIntegerField(verbose_name='Stock')),
                ('enabled', models.BooleanField(default=True, verbose_name='Disponible')),
                ('details', models.CharField(blank=True, max_length=128, null=True, verbose_name='Detalles')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categories', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'unique_together': {('category', 'code', 'item', 'description')},
            },
        ),
    ]
