# Generated by Django 5.0.2 on 2024-02-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Categoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Code')),
                ('item', models.CharField(max_length=128, verbose_name='Item')),
                ('description', models.CharField(max_length=512, verbose_name='Description')),
                ('stock', models.SmallIntegerField(verbose_name='Stock')),
                ('enabled', models.BooleanField(verbose_name='Disponible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categories', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
    ]
