# Generated by Django 5.0.2 on 2024-05-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_students_class_name_students_class_name'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.materials')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Gives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateField(auto_now_add=True, verbose_name='Fecha de prestamos')),
                ('date_back', models.DateField(verbose_name='Fecha de devolución')),
                ('is_give', models.BooleanField(verbose_name='Entregado')),
                ('is_back', models.BooleanField(verbose_name='Devuelto')),
                ('observations', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Observaciones')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.students')),
                ('all_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.items')),
            ],
            options={
                'verbose_name': 'Prestamos',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
