# Generated by Django 5.0.2 on 2024-02-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_gives_gives'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='gives',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.gives', verbose_name='Prestamo'),
            preserve_default=False,
        ),
    ]
