# Generated by Django 5.0.2 on 2024-05-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_gives_all_items_items_gives'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('gives', 'item')},
        ),
    ]
