# Generated by Django 5.0.2 on 2024-02-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_gives_student'),
        ('store', '0003_alter_materials_gives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='gives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.gives', verbose_name='Prestamo'),
        ),
    ]
