# Generated by Django 5.0.2 on 2024-05-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_items_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='gives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_gives_gives', to='store.gives', verbose_name='Prestamo'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_gives_item', to='store.materials', verbose_name='Items'),
        ),
    ]
