# Generated by Django 5.0.2 on 2024-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_materials_gives'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materials',
            unique_together={('category', 'code', 'item', 'description')},
        ),
        migrations.AlterField(
            model_name='materials',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='item',
            field=models.CharField(max_length=128, unique=True, verbose_name='Item'),
        ),
        migrations.RemoveField(
            model_name='materials',
            name='gives',
        ),
    ]
