# Generated by Django 5.0.2 on 2024-05-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_items_gives_alter_items_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gives',
            name='is_give',
        ),
    ]
