# Generated by Django 5.0.2 on 2024-05-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_students_class_name_students_class_name'),
        ('store', '0006_remove_gives_is_give'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gives',
            name='date_out',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de prestamo'),
        ),
        migrations.AlterField(
            model_name='gives',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.students', verbose_name='Estudiante'),
        ),
    ]
