# Generated by Django 5.0.2 on 2024-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_items_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='habilitado'),
        ),
    ]
