# Generated by Django 5.0.2 on 2024-05-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_items_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='enabled',
        ),
    ]
