# Generated by Django 5.0.2 on 2024-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_items_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='count_save',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad guardada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='count',
            field=models.SmallIntegerField(verbose_name='Cantidad'),
        ),
    ]
