# Generated by Django 5.0.2 on 2024-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_items_count_save_alter_items_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='count_save',
            field=models.SmallIntegerField(default=0, verbose_name='Cantidad guardada'),
        ),
    ]
