# Generated by Django 5.0.2 on 2024-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_items_count_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='count',
            field=models.SmallIntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
