# Generated by Django 5.0.2 on 2024-03-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Carrera')),
                ('code', models.CharField(max_length=8, verbose_name='Codigo')),
                ('sede_code', models.CharField(choices=[('0', 'BES'), ('1', 'TPC'), ('2', 'PAP')], max_length=1, verbose_name='Codigo de sede')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Asignatura')),
                ('code', models.CharField(max_length=16, verbose_name='Codigo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('stage', models.CharField(choices=[('0', '1°'), ('1', '2°')], max_length=1, verbose_name='Semestre')),
                ('teacher', models.CharField(blank=True, max_length=32, null=True, verbose_name='Profesor')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to='attendance.schools', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=32, verbose_name='Apellido')),
                ('rut', models.CharField(blank=True, max_length=10, null=True, verbose_name='RUT')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('class_name', models.ManyToManyField(blank=True, related_name='class_student', to='attendance.classes', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'unique_together': {('name', 'last_name', 'rut')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(auto_now_add=True, verbose_name='Ingreso')),
                ('time_inside', models.TimeField(verbose_name='Tiempo estimado de permanencia')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.students', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('challenge', models.CharField(blank=True, max_length=32, null=True, verbose_name='Reto')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_team', to='attendance.classes', verbose_name='Asignatura')),
                ('team_name', models.ManyToManyField(blank=True, related_name='team_student', to='attendance.students', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
