# Generated by Django 5.0.2 on 2024-02-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ingreso'),
        ),
    ]
