# Generated by Django 5.0.2 on 2024-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologicEnabled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('score', models.SmallIntegerField(verbose_name='Puntaje')),
                ('status', models.BooleanField(verbose_name='Estado')),
                ('tecno_enabled', models.ManyToManyField(blank=True, related_name='enabled_student', to='attendance.classes', verbose_name='Habilitador')),
            ],
            options={
                'verbose_name': 'Habilitador',
                'verbose_name_plural': 'Habilitadores',
            },
        ),
    ]
