# Generated by Django 5.0.2 on 2024-03-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_students_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='attendance.teams', verbose_name='Equipo'),
        ),
    ]
