# Generated by Django 5.0.2 on 2024-04-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_tecnologicenabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologicenabled',
            name='tecno_enabled',
            field=models.ManyToManyField(blank=True, related_name='enabled_student', to='attendance.students', verbose_name='Habilitador'),
        ),
    ]
