# Generated by Django 5.0.2 on 2024-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_students_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='team',
        ),
        migrations.AddField(
            model_name='teams',
            name='students',
            field=models.ManyToManyField(to='attendance.students'),
        ),
    ]
