# Generated by Django 5.0.2 on 2024-04-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_tecnologicenabled_tecno_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologicenabled',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Puntaje'),
        ),
    ]
