# Generated by Django 5.0.2 on 2024-03-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_classes_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
    ]
