# Generated by Django 5.0.2 on 2024-04-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_topicenabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnoEnabledResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_result', models.SmallIntegerField(blank=True, null=True, verbose_name='Puntaje obtenido')),
                ('status', models.BooleanField(verbose_name='Estado')),
                ('tecno_enabled', models.ManyToManyField(blank=True, related_name='enabled_student', to='attendance.students', verbose_name='Habilitador')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_enabled', to='attendance.topicenabled', verbose_name='Nombre habilitador')),
            ],
            options={
                'verbose_name': 'Resultado Habilitadores',
                'verbose_name_plural': 'Resultados Habilitadores',
            },
        ),
        migrations.DeleteModel(
            name='TecnologicEnabled',
        ),
    ]
