# Generated by Django 5.0.2 on 2024-04-03 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_tecnoenabledresults_delete_tecnologicenabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnoenabledresults',
            name='tecno_enabled',
        ),
        migrations.AddField(
            model_name='tecnoenabledresults',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enabled', to='attendance.students', verbose_name='Estudiante'),
        ),
    ]
