# Generated by Django 5.0.2 on 2024-03-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_teams_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_name', to='attendance.classes', verbose_name='Asignatura'),
        ),
    ]
