# Generated by Django 5.0.2 on 2024-04-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_tecnoenabledresults_tecno_enabled_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tecnoenabledresults',
            unique_together={('student', 'topic')},
        ),
    ]
