# Generated by Django 5.0.2 on 2024-03-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_teams_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='students',
            field=models.ManyToManyField(related_name='students_team', to='attendance.students', verbose_name='Estudiantes'),
        ),
    ]
