# Generated by Django 5.0.2 on 2024-03-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_teams_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='challenge',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Reto'),
        ),
        migrations.AlterField(
            model_name='students',
            name='rut',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_team', to='attendance.students', verbose_name='Estudiantes'),
        ),
    ]
