# Generated by Django 5.0.2 on 2024-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_tecnoenabledresults_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='challenge',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Reto'),
        ),
    ]
