# Generated by Django 5.0.2 on 2024-04-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_teams_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnoenabledresults',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_enabled', to='attendance.students', verbose_name='Estudiante'),
        ),
    ]
