# Generated by Django 5.0.2 on 2024-04-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_tecnoenabledresults_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='class_name',
        ),
        migrations.AddField(
            model_name='students',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_student', to='attendance.classes', verbose_name='Asignatura'),
        ),
    ]
