# Generated by Django 5.0.2 on 2024-07-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_students_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicenabled',
            name='tecnologic',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tecnologia'),
        ),
    ]
