# Generated by Django 5.0.2 on 2024-07-22 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_topicenabled_tecnologic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ame', models.CharField(max_length=32, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
            },
        ),
        migrations.RemoveField(
            model_name='topicenabled',
            name='tecnologic',
        ),
        migrations.AddField(
            model_name='teams',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.technology'),
        ),
        migrations.AddField(
            model_name='topicenabled',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.technology'),
        ),
    ]
