# Generated by Django 5.0.2 on 2024-07-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_rename_ame_technology_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='details',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Observaciones'),
        ),
    ]
