# Generated by Django 5.0.2 on 2024-07-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_teams_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
