# Generated by Django 5.0.2 on 2024-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_teams_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Informe'),
        ),
    ]
