# Generated by Django 5.0.2 on 2024-07-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_teams_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Nota'),
        ),
    ]
