# Generated by Django 5.0.2 on 2024-02-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gives',
            name='gives',
        ),
    ]
