# Generated by Django 5.0.2 on 2024-02-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('inventory', '0005_alter_gives_student'),
        ('store', '0005_alter_materials_unique_together_alter_materials_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gives',
            name='student',
        ),
        migrations.CreateModel(
            name='GiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.materials', verbose_name='Materiales')),
            ],
        ),
        migrations.CreateModel(
            name='GivesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.gives', verbose_name='Prestamos')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.students', verbose_name='Estudiante')),
            ],
        ),
    ]
