# Generated by Django 5.0.2 on 2024-02-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('inventory', '0007_rename_gives_givesitems_give'),
    ]

    operations = [
        migrations.AddField(
            model_name='gives',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.students', verbose_name='Estudiante'),
            preserve_default=False,
        ),
    ]
