# Generated by Django 5.0.2 on 2024-02-09 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_givesitems_give_remove_givesitems_student_and_more'),
        ('store', '0005_alter_materials_unique_together_alter_materials_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givesitems',
            name='give',
        ),
        migrations.AddField(
            model_name='givesitems',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.materials', verbose_name='Materiales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='givesitems',
            name='mount',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
