# Generated by Django 5.0.2 on 2024-02-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_givesitems_give_givesitems_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='givesitems',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.DeleteModel(
            name='GiveItem',
        ),
    ]
